apiToken: tokeeeen
sshKeys: [1337, 4711]
diameter: 0
#regions: ["nyc1", "sfo3", "fra1", "ams3", "syd1", "sgp1"]
regions: ["nyc1", "nyc2", "nyc3", "sfo1", "sfo2", "sfo3", "blr1", "fra1", "ams2", "ams3", "syd1", "sgp1", "lon1", "tor1"]
startupScript: startup.sh
storageLocation : https://storage.test.de
accessKey: key
secretKey: key
storageBucket: telescope/upload
digitalOcean:
  size: s-1vcpu-1gb
  os: ubuntu-24-04-x64

