diameter: 0

storage:
  storageLocation : https://storage.server.eu
  accessKey: accesskey
  secretKey: secretley
  storageBucket: telescope/upload

digitalOcean:
  apiToken: eintokeeeeeeeeeeeeen
  sshKeys: [0815, 4711]
  size: s-1vcpu-1gb
  os: ubuntu-24-04-x64
  regions: ["nyc1", "nyc2", "nyc3", "sfo1", "sfo2", "sfo3", "blr1", "fra1", "ams2", "ams3", "syd1", "sgp1", "lon1", "tor1"]
  startupScript: startup.sh
  numVMs: 0

mockProvider:
  apiToken: halloweltichbineinapitokenjaja
  impFile: mock.gob
  impStr: stringssindwichtig
  regions: ["ms1", "ms2", "ude-e1", "ude-d1", "tum1", "tum2", "kit1", "kit2", "caida2", "caida3", "utwente-1"]
  diameter: 5

